version: "3.8"

services:
  relational-data:
    build: ./schemas/relational-table
    image: relational-data:1.0.0
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M

  text-tag-array-data:
    build: ./schemas/tag-array-text
    image: text-tag-array-data:1.0.0
    ports:
      - "5433:5432"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M

  integer-tag-array-data:
    build: ./schemas/tag-array-integer
    image: integer-tag-array-data:1.0.0
    ports:
      - "5434:5432"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 256M
